[package]
name = "libncurses"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://invisible-mirror.net/archives/ncurses/current/"

[[package.metadata.build-package.external-files]]
url = "https://invisible-mirror.net/archives/ncurses/current/ncurses-6.5-20240713.tgz"
sha512 = "d0a9874aec4d32e2dfd0f7215d75caa004a983b4da9a68bfd6508bd75c85074b9bbc21609d5deaf5e741a1d8d8766aa5290958d9bbb2718dd359d5d3a264234c"

[build-dependencies]
glibc = { path = "../glibc" }
