[package]
name = "ecr-credential-provider"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/kubernetes/cloud-provider-aws/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/kubernetes/cloud-provider-aws/archive/v1.25.15/cloud-provider-aws-1.25.15.tar.gz"
sha512 = "1e4ee33900d3ec655ce9f5788bb8f173621f187b130464bef196ef6e18a61a49d9501f5492909922a34b086fcffbb0cb369cfa8b941efbb0c38ffb0abe6c17dc"
bundle-modules = [ "go" ]

[build-dependencies]
glibc = { path = "../glibc" }
