[package]
name = "ecr-credential-provider"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/kubernetes/cloud-provider-aws/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/kubernetes/cloud-provider-aws/archive/v1.25.16/cloud-provider-aws-1.25.16.tar.gz"
sha512 = "be2937871764a59b5e8dcca0d5a08e665c18ff56f859f4e5eb41cd5d1cdda9bfb0d0b30fd53fa9024cfa90526bddb581ea01375b7f8884cad2314521752d3068"
bundle-modules = [ "go" ]

[build-dependencies]
glibc = { path = "../glibc" }
