[package]
name = "nvme-cli"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/linux-nvme/nvme-cli/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/linux-nvme/nvme-cli/archive/v2.10.2/nvme-cli-2.10.2.tar.gz"
sha512 = "98ecb2488cdf21c83004204f4cb7e7d9327fef5a33e5a37d977c659d76be3cef861473676fa7fbd1d40f38742b365b98431e17d9b0318ddb4cc407953acdde87"

[build-dependencies]
glibc = { path = "../glibc" }
libnvme = { path = "../libnvme" }
