[package]
name = "dbus-broker"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/bus1/dbus-broker/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/bus1/dbus-broker/releases/download/v36/dbus-broker-36.tar.xz"
sha512 = "47ff345e27ae2ba41f43a4a6eb09b813583ef43392d1dfa2fc1805578c0ed3a1e414c3eae63f78ca3806904dc017a138e283aa32ba973de51ed613050b244a0f"

[build-dependencies]
glibc = { path = "../glibc" }
libexpat = { path = "../libexpat" }
libselinux = { path = "../libselinux" }
systemd = { path = "../systemd" }
