[package]
name = "early-boot-config-provider"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>", "Sam Berning <bernings@amazon.com"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
async-trait.workspace = true
env_logger.workspace = true
flate2 = { workspace = true, features = ["rust_backend"] }
log.workspace = true
retry-read.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
snafu.workspace = true
toml.workspace = true

[build-dependencies]
generate-readme.workspace = true

[dev-dependencies]
hex-literal.workspace = true
lazy_static.workspace = true
