[package]
name = "makedumpfile"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/makedumpfile/makedumpfile/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/makedumpfile/makedumpfile/archive/1.7.5/makedumpfile-1.7.5.tar.gz"
sha512 = "6bb84a87959d2aa530f952acacacc669e888b6a0ae5fe3c6c627647a0e2566a73f05c70ba7b2428f9c740bfe40a773792bb302039ab62c0fa646e148c69f7c6f"

[build-dependencies]
glibc = { path = "../glibc" }
libelf = { path = "../libelf" }
libz = { path = "../libz" }
