[package]
name = "makedumpfile"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/makedumpfile/makedumpfile/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/makedumpfile/makedumpfile/archive/1.7.4/makedumpfile-1.7.4.tar.gz"
sha512 = "6c3455b711bd4e120173ee07fcc5ff708ae6d34eaee0f4c135eca7ee0e0475b4d391429c23cf68e848b156ee3edeab956e693a390d67ccc634c43224c7129a96"

[build-dependencies]
glibc = { path = "../glibc" }
libelf = { path = "../libelf" }
libz = { path = "../libz" }
