[package]
name = "libcap"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://cdn.kernel.org/pub/linux/libs/security/linux-privs/libcap2/"
# Changelog can be found here: https://sites.google.com/site/fullycapable/release-notes-for-libcap

[[package.metadata.build-package.external-files]]
url = "https://cdn.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.70.tar.gz"
sha512 = "2a4a5959958989e6a0d54ea795a706b0f12596778ac660b19b7b1479910af01b4d870111b060dac0b1cd4671b98d815ea5953cefd4edde1a0ba9efe22f897842"

[build-dependencies]
glibc = { path = "../glibc" }
libattr = { path = "../libattr" }
