[package]
name = "mdadm"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://cdn.kernel.org/pub/linux/utils/raid/mdadm/"

[[package.metadata.build-package.external-files]]
url = "https://cdn.kernel.org/pub/linux/utils/raid/mdadm/mdadm-4.3.tar.xz"
sha512 = "e44977f2f80d2471cb313803a60c92dafe8282ac06bbbfd41ae90ca493c64a3da94db924538788d045fd7f0667333912dabedb0b070f9abf5c0540b32e0fa08f"

[build-dependencies]
glibc = { path = "../glibc" }
systemd = { path = "../systemd" }
