[package]
name = "storewolf"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
constants = { path = "../../constants", version = "0.1" }
bottlerocket-release = { path = "../../bottlerocket-release", version = "0.1" }
datastore = { path = "../datastore", version = "0.1" }
log = "0.4"
models = { path = "../../models", version = "0.1" }
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }
semver = "1"
simplelog = "0.12"
snafu = "0.8"
toml = "0.8"

[dependencies.bottlerocket-modeled-types]
git = "https://github.com/bottlerocket-os/bottlerocket-settings-sdk"
tag = "bottlerocket-settings-models-v0.1.0"
version = "0.1.0"

[build-dependencies]
generate-readme = { version = "0.1", path = "../../generate-readme" }

[[bin]]
name = "storewolf"
path = "src/main.rs"

[lib]
name = "storewolf"
path = "src/lib.rs"
