[package]
name = "ecs-agent"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

# ECS agent
[package.metadata.build-package]
releases-url = "https://github.com/aws/amazon-ecs-agent/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/aws/amazon-ecs-agent/archive/v1.82.3/amazon-ecs-agent-1.82.3.tar.gz"
sha512 = "a26fdbe5c6cb96f5357afea701a97ccaa208ab3ae2149cd0205aa34b8686edd38c194ee8e0389b5385295bf284fcc1bee73dcacc2313c4b560e807eb27c1bafa"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }

# RPM Requires
[dependencies]
# `docker-engine` is only needed at runtime, and is included in the variant
# definition.
# docker-engine = { path = "../docker-engine" }
# `iptables` is only needed at runtime, and is pulled in by `release`.
# iptables = { path = "../iptables" }
amazon-ssm-agent = { path = "../amazon-ssm-agent" }
