[package]
name = "strace"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://strace.io/files"

[[package.metadata.build-package.external-files]]
url = "https://strace.io/files/6.9/strace-6.9.tar.xz"
sha512 = "aa80b9b6ec41082f1710f2327f7a22003cdce6d95ab0e5083ada9c5b7b40b8f7cbc7dc6c017878dc0e42c52e405e98ed1488c51d17bc3538989ff4be2c2411e1"

[build-dependencies]
glibc = { path = "../glibc" }
