[package]
name = "strace"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://strace.io/files"

[[package.metadata.build-package.external-files]]
url = "https://strace.io/files/6.8/strace-6.8.tar.xz"
sha512 = "c477724a77112a74a5236a38b7dbaa9b6199622a1d21cc6253cac80dc4ddea78aeaf8cddf4a51ee4119e00e1adaf95f64f64e20d9775ec3edd77cd82c8f7b30e"

[build-dependencies]
glibc = { path = "../glibc" }
