[package]
name = "libelf"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://sourceware.org/elfutils/ftp/"

[[package.metadata.build-package.external-files]]
url = "https://sourceware.org/elfutils/ftp/0.191/elfutils-0.191.tar.bz2"
sha512 = "e22d85f25317a79b36d370347e50284c9120c86f9830f08791b7b6a7b4ad89b9bf4c7c71129133b8d193a0edffb2a2c17987b7e48428b9670aff5ce918777e04"

[build-dependencies]
glibc = { path = "../glibc" }
libz = { path = "../libz" }
