[package]
name = "xfsprogs"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://mirrors.edge.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/"

[[package.metadata.build-package.external-files]]
url = "http://kernel.org/pub/linux/utils/fs/xfs/xfsprogs/xfsprogs-6.7.0.tar.xz"
sha512 = "4f543e4c5c4e88e4f9ce16b82ca1151330f687469368fe7470b68e8bb21d1d3c7280eb2e691d3bdf24ae3d4fa2ee5764dc34637198bca0d4ffa65eea2f10ac74"

[build-dependencies]
glibc = { path = "../glibc" }
libinih = { path = "../libinih" }
liburcu = { path = "../liburcu" }
util-linux = { path = "../util-linux" }

# RPM Requires
[dependencies]
# none
