[package]
name = "thar-be-updates"
version = "0.1.0"
authors = ["Erikson Tung <etung@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
bottlerocket-release = { path = "../../bottlerocket-release", version = "0.1" }
chrono = { version = "0.4", default-features = false, features = ["std", "serde", "clock"] }
fs2 = "0.4"
log = "0.4"
nix = "0.26"
num-derive = "0.4"
num-traits = "0.2"
semver = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_plain = "1"
signpost = { path = "../../updater/signpost", version = "0.1" }
simplelog = "0.12"
snafu = "0.8"
tempfile = "3"
toml = "0.8"
update_metadata = { path = "../../updater/update_metadata", version = "0.1" }

[dependencies.bottlerocket-modeled-types]
git = "https://github.com/bottlerocket-os/bottlerocket-settings-sdk"
tag = "bottlerocket-settings-models-v0.2.0"
version = "0.2.0"

[build-dependencies]
generate-readme = { version = "0.1", path = "../../generate-readme" }
