[package]
name = "thar-be-updates"
version = "0.1.0"
authors = ["Erikson Tung <etung@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
bottlerocket-release.workspace = true
chrono = { workspace = true, features = ["clock", "serde", "std"] }
fs2.workspace = true
log.workspace = true
nix.workspace = true
num-derive.workspace = true
num-traits.workspace = true
semver = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_plain.workspace = true
signpost.workspace = true
simplelog.workspace = true
snafu.workspace = true
tempfile.workspace = true
toml.workspace = true
update_metadata.workspace = true
bottlerocket-modeled-types.workspace = true

[build-dependencies]
generate-readme.workspace = true
