[package]
name = "libnl"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/thom311/libnl/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/thom311/libnl/archive/libnl3_10_0.tar.gz"
sha512 = "4950bf94371bc238df416546b63a0181fd0f684c4476b6e9dd99e14a63a42a3e5d1ec2b7bfe7249aa31e4ae5d43c33575031ec3eafba3de5a63e11936f66e89e"

[build-dependencies]
glibc = { path = "../glibc" }
