[package]
name = "ec2-identity-doc-user-data-provider"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>", "Sam Berning <bernings@amazon.com>"]
edition = "2021"
license = "Apache-2.0 OR MIT"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
imdsclient = { path = "../../imdsclient", version = "0.1" }
log = "0.4"
serde_json = "1"
snafu = "0.7"
tokio = { version = "~1.32", default-features = false, features = ["process", "macros", "rt-multi-thread"] }  # LTS
user-data-provider = { path = "../../api/user-data-provider", version = "0.1" }
