[package]
name = "vmware-cd-rom-user-data-provider"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>", "Sam Berning <bernings@amazon.com>"]
edition = "2021"
license = "Apache-2.0 OR MIT"
publish = false
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
base64.workspace = true
log.workspace = true
serde = { workspace = true, features = ["derive"] }
serde-xml-rs.workspace = true
snafu.workspace = true
early-boot-config-provider.workspace = true

[build-dependencies]
generate-readme.workspace = true
