[package]
# "." is not allowed in crate names, but we want a friendlier name for the
# directory and spec file, so we override it below.
name = "ecr-credential-provider-1_27"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
package-name = "ecr-credential-provider-1.27"
releases-url = "https://github.com/kubernetes/cloud-provider-aws/releases"

[[package.metadata.build-package.external-files]]
url = "https://codeload.github.com/kubernetes/cloud-provider-aws/tar.gz/v1.27.8"
path = "cloud-provider-aws-1.27.8.tar.gz"
sha512 = "31a4627760cfc173a216e902d403e0dd47bbdf69437f3b64545b303bd66e6b7025db5e312d96432a2002bc70921cd1394d6923e2e1ac36f8adb610664d65a29f"
bundle-modules = [ "go" ]

[build-dependencies]
glibc = { path = "../glibc" }
