[package]
name = "libaudit"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/linux-audit/audit-userspace/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/linux-audit/audit-userspace/archive/v3.1.4/audit-userspace-3.1.4.tar.gz"
sha512 = "76cbc0bdde91adf8f8870784ea0741a01869c68dc0d3fb9c5815d5aa3e96ead2fd28ba06b98e5c70b8fe2113e7c43defd48af01ec82cba13f3907698067f964d"

[build-dependencies]
glibc = { path = "../glibc" }
