[package]
name = "libtirpc"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://sourceforge.net/projects/libtirpc/files/libtirpc/"

[[package.metadata.build-package.external-files]]
url = "https://downloads.sourceforge.net/libtirpc/libtirpc-1.3.5.tar.bz2"
sha512 = "c80a953671c5692294efe7425e41c7f12bd4c430f473f9ea71883168cb4a69111f0018122bd0e7982e18f4576e45d4977ce0790743382faae006c446813d2a4f"

[build-dependencies]
glibc = { path = "../glibc" }
