[package]
name = "iptables"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://www.netfilter.org/projects/iptables/files"

[[package.metadata.build-package.external-files]]
url = "https://www.netfilter.org/projects/iptables/files/iptables-1.8.10.tar.xz"
sha512 = "71e6ed2260859157d61981a4fe5039dc9e8d7da885a626a4b5dae8164c509a9d9f874286b9468bb6a462d6e259d4d32d5967777ecefdd8a293011ae80c00f153"

[build-dependencies]
glibc = { path = "../glibc" }
libmnl = { path = "../libmnl" }
libnetfilter_conntrack = { path = "../libnetfilter_conntrack" }
libnfnetlink = { path = "../libnfnetlink" }
libnftnl = { path = "../libnftnl" }
