[package]
name = "socat"
version = "0.1.0"
edition = "2018"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[[package.metadata.build-package.external-files]]
url = "http://www.dest-unreach.org/socat/download/socat-1.8.0.0.tar.gz"
sha512 = "edf459a9f1907a14025e13b3101ad29787f9a72795cffcd00017ce98847562884db29a95b9ae478a6a50868137548b142947c43fb18e975eb5853a763c42902c"

[build-dependencies]
glibc = { path = "../glibc" }
