[package]
name = "aws-signing-helper"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/aws/rolesanywhere-credential-helper/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/aws/rolesanywhere-credential-helper/archive/v1.2.0/rolesanywhere-credential-helper-v1.2.0.tar.gz"
sha512 = "c2c7fa2fb319aea0036bf334c59cf2a10520da56a45a3e04a99870becfee5099eeb655933b507d2627ebcfde969f1150f0025ace6e06b88bfa801ee847324d30"
bundle-modules = [ "go" ]

[build-dependencies]
glibc = { path = "../glibc" }
