[package]
name = "findutils"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://ftp.gnu.org/pub/gnu/findutils"

[[package.metadata.build-package.external-files]]
url = "https://ftp.gnu.org/pub/gnu/findutils/findutils-4.10.0.tar.xz"
sha512 = "b8b683d21cd26c6da4f41c56e83cadbda4780f8610a2bbd4b4e34bb1f339c3209721974b03e076d5eef0331fd876d947b398197aad37c29bbcc2e0405c641b34"

[build-dependencies]
glibc = { path = "../glibc" }
libselinux = { path = "../libselinux" }
