[package]
name = "libnvme"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/linux-nvme/libnvme/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/linux-nvme/libnvme/archive/v1.10/libnvme-1.10.tar.gz"
sha512 = "44e8a407c9fda8c296163832c14ba167caab53eab315bd2dee94275458532429f12a35e0adef1356420d83127e658a354ce65ac946acaa53bef2d46a8189054c"

[build-dependencies]
glibc = { path = "../glibc" }
