[package]
name = "util-linux"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://www.kernel.org/pub/linux/utils/util-linux"

[[package.metadata.build-package.external-files]]
url = "https://www.kernel.org/pub/linux/utils/util-linux/v2.40/util-linux-2.40.2.tar.xz"
sha512 = "ffe20b915a518a150401d429b0338bc7022190e4ca0ef91a6d9eea345db8c1e11ad01784163b8fcf978506f3f5cad473f29d5d4ef93a4c66a5ae0ebd9fb0c8f2"

[build-dependencies]
glibc = { path = "../glibc" }
libacl = { path = "../libacl" }
libselinux = { path = "../libselinux" }
libxcrypt = { path = "../libxcrypt" }
libncurses = { path = "../libncurses" }
