[package]
name = "soci-snapshotter"
version = "0.1.0"
publish = false
build = "../build.rs"
edition = "2021"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/awslabs/soci-snapshotter/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/awslabs/soci-snapshotter/archive/refs/tags/v0.6.1.tar.gz"
sha512 = "5d789e79be7157aed7a6af0bdde622d0d60bef3c268971d4eb980d4f32dbcad651c99912d94165f500fdf63498cc4e782083f046412b941ced7522e3ee32588d"
bundle-root-path = "soci-snapshotter-0.6.1/cmd"
bundle-output-path = "bundled-cmd.tar.gz"
bundle-modules = [ "go" ]

[[package.metadata.build-package.external-files]]
url = "https://github.com/awslabs/soci-snapshotter/archive/refs/tags/v0.6.1.tar.gz"
sha512 = "5d789e79be7157aed7a6af0bdde622d0d60bef3c268971d4eb980d4f32dbcad651c99912d94165f500fdf63498cc4e782083f046412b941ced7522e3ee32588d"
bundle-modules = [ "go" ]

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }
libz = { path = "../libz" }
