[package]
name = "vmware-cd-rom-user-data-provider"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>", "Sam Berning <bernings@amazon.com>"]
edition = "2021"
license = "Apache-2.0 OR MIT"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
base64 = "0.13"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde-xml-rs = "0.6"
snafu = "0.7"
tokio = { version = "~1.32", default-features = false, features = ["process", "macros", "rt-multi-thread"] }  # LTS
user-data-provider = { path = "../../api/user-data-provider", version = "0.1" }
