[package]
name = "bash"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://ftp.gnu.org/gnu/bash"

[[package.metadata.build-package.external-files]]
url = "https://ftp.gnu.org/gnu/bash/bash-5.2.32.tar.gz"
sha512 = "92a66ff5159964d430a29027a259a9f4ab45e22ee57483d21ace58a731182627092fbf3032e1cd531ff359cf91c691b088eb647f41b06e113e53c01a2f057405"

[build-dependencies]
glibc = { path = "../glibc" }
libncurses = { path = "../libncurses" }
readline = { path = "../readline" }
